# Example docker-compose for dockershocker

services:
  your_service:
    image: your_image
    labels:
      dockershocker.enabled: true
      dockershocker.timeout_minutes: 30

  dockershocker:
    image: sammcj/dockershocker:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    ports:
      - 8080:8080
    environment:
      LOG_LEVEL: debug
      DOCKER_SOCKET: tcp://dockerproxy:2375
      PORT: 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # traefik:
  #  ...

  # dockerproxy:
  #  ...